### ISSUE TITLE
Specified column not found in the data frame

### ISSUE THREAD

**Issue by wa123219** [grenaud/vgan#12]
Hello developer, I successfully ran euka using the provided fastq file (wget https://github.com/grenaud/vgan/raw/main/test/input_files/euka/three_dhigh_100.fq.gz), but encountered an error when running ./visualize_detected_taxa.sh euka_output:

Loading required package: ggplot2  
Error: Specified column not found in the data frame.  
Execution halted  
Loading required package: ggplot2  
Error: Specified column not found in the data frame.  
Execution halted

**Comment by nicolaavogel** [comment]
Hi! 

This error in the plotting script is due to some not perfect coding on my side. I updated the plotting script "plot_taxa.R" that is called by visualize_detected_taxa.sh. If you could redownload, and give it a try - I hope I fixed it now! :)

**Comment by wa123219** [comment]
Hello developer, I'm still encountering an error after trying the modified "plot_taxa.R" script:
Loading required package: ggplot2
DEBUG: Column not found. args[2] = Myotis
DEBUG: colnames(ne) =
Error: Specified column not found in the data frame.
Execution` halted
Loading required package: ggplot2
DEBUG: Column not found. args[2] = Ursidae
DEBUG: colnames(ne) =
Error: Specified column not found in the data frame.
Execution halted**

So I tried adding `print(colnames(ne))`to line 42 of the code, and the result showed `NULL`. I suspected that the column names were not preserved after transposing the dataframe. To address this, I modified line 35 to `df <- as.data.frame(t(df))`, but this resulted in incorrect inSize plots: 

![Image](https://github.com/user-attachments/assets/28221f78-709e-427c-970c-f819ac3983b0)

However, when I removed line 35 of the code, did not transpose the database, and this time the program ran successfully, printing a successful picture:

![Image](https://github.com/user-attachments/assets/1709f729-8bfd-4e31-a7bd-c3738add3abf)

is it right?

**Comment by nicolaavogel** [comment]
Hi, yes, this is correct! 
Thank you so much for reporting this to us! I will incorporate your changes into our scripts. :)
